apiVersion: v1
data:
  enable-snippets: "true"
  allow-snippet-annotations: "true"
  server-snippet: |
    error_page 404 = @json_error;
    location @json_error {
        internal;
        add_header Content-Type application/json;
        return 404 '{"error": "Resource not found"}';
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"allow-snippet-annotations":"false","server-snippet":"error_page 404 = @json_error;\nlocation @json_error {\n    internal;\n    add_header Content-Type application/json;\n    return 404 '{\"error\": \"Resource not found\"}';\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{"meta.helm.sh/release-name":"ingress-nginx","meta.helm.sh/release-namespace":"ingress-nginx"},"labels":{"app.kubernetes.io/component":"controller","app.kubernetes.io/instance":"ingress-nginx","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"ingress-nginx","app.kubernetes.io/part-of":"ingress-nginx","app.kubernetes.io/version":"1.11.1","helm.sh/chart":"ingress-nginx-4.11.1"},"name":"ingress-nginx-controller","namespace":"ingress-nginx"}}
    meta.helm.sh/release-name: ingress-nginx
    meta.helm.sh/release-namespace: ingress-nginx
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.11.1
    helm.sh/chart: ingress-nginx-4.11.1
  name: ingress-nginx-controller
  namespace: ingress-nginx
